# Generated by Django 5.0.1 on 2025-10-04 01:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_client_current_plan_client_stripe_customer_id_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='client',
            old_name='stripe_customer_id',
            new_name='paypal_customer_id',
        ),
        migrations.RenameField(
            model_name='client',
            old_name='stripe_subscription_id',
            new_name='paypal_subscription_id',
        ),
        migrations.AddField(
            model_name='user',
            name='bio',
            field=models.TextField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='client',
            name='account_manager',
            field=models.CharField(default='Admin', max_length=255),
        ),
        migrations.AlterField(
            model_name='client',
            name='current_plan',
            field=models.CharField(blank=True, choices=[('starter', 'Starter Plan'), ('pro', 'Pro Plan'), ('premium', 'Premium Plan'), ('none', 'No Plan Selected')], default='none', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='client',
            name='monthly_fee',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='client',
            name='next_payment',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='client',
            name='package',
            field=models.CharField(default='No Plan Selected', max_length=255),
        ),
        migrations.AlterField(
            model_name='client',
            name='payment_status',
            field=models.CharField(choices=[('paid', 'Paid'), ('overdue', 'Overdue'), ('pending', 'Pending'), ('none', 'No Payment Required')], default='none', max_length=20),
        ),
        migrations.AlterField(
            model_name='client',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('pending', 'Pending'), ('paused', 'Paused'), ('cancelled', 'Cancelled')], default='pending', max_length=20),
        ),
    ]
